### ISSUE TITLE
wishful: will there be forward and reverse kinematics functions?

### ISSUE THREAD

**Issue by dsyleixa** [kk6axq/BraccioV2#2]
hello,
will there be forward and reverse kinematics functions?

**Comment by kk6axq** [comment]
This is a possibility in the future. Currently, the library is being developed for use in a university course, with the possibility of students using the library to develop their own inverse and forward kinematic models. I'll add this as a possible feature for release 0.3.0. If you would like to contribute some of the code for that, please go ahead and submit a pull request.

**Comment by kk6axq** [comment]
After some further investigation, this appears to be too computationally intensive for an Uno board. If you are interested in pursuing this, by all means, submit a pull request, but I won't be actively working on this feature.

**Comment by dsyleixa** [comment]
it's not meant for an UNO bu for a DUE, an ESP32, or an M4!
Don't support your libs ARM Cortex and ESP32 boards?

**Comment by kk6axq** [comment]
I understand your intention of using kinematics on a higher power board, but the primary purpose of this library is for use in a university setting using Arduino UNO boards. I also only have access to 328P based boards in the Arduino form factor for development. If you are interested in developing support for kinematics with higher powered boards, create a fork or other library and go at it.

To answer your question on whether this library supports ARM/ESP boards, it does from the software side, provided they have the Servo library, however the hardware board must be compatible with the Braccio shield.

**Comment by dsyleixa** [comment]
ok, I see your standpoint, but UNOs are far too puny and outdated, Arduino  is providing the DUE since about 8 years and now even M4 boards (Nano 33 BLE), feat.  a fpu and preemptive multithreading. Also Teensy is providing ARM Cortex boards with single and double fpu. The future belongs to 32bit  boards, not the rediculous 8bit AVRs.

**Comment by kk6axq** [comment]
I agree that the industry is moving towards higher power boards, but the intended customer of this library, and the customer whom this library is intended to support, uses the Uno, whether I, you, or anybody else likes it, and that is who the library will continue to support.
